version: "3"
services:
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app
  account-api:
    build:
      context: ./account-api
    ports:
      - "3003:3003"
    networks:
      - mern-app
    depends_on:
      - mongo
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local